import type { PresentationSlide } from "@/lib/admin-presentation-types";

export const ACADEMIC_SLIDES_3: PresentationSlide[] = [
  {
    kicker: "Use Case",
    title: "Use Case Diagram (PlantUML)",
    figures: [
      {
        key: "usecase-tute.png",
        alt: "Use case Tử Tế Fund",
        caption: "",
      },
    ],
    tree: [
      { path: "U01 @startuml uc-tute", note: "" },
      { path: "U02 left to right direction", note: "" },
      { path: "U03 actor Guest", note: "" },
      { path: "U04 actor Backer", note: "" },
      { path: "U05 actor Creator", note: "" },
      { path: "U06 actor Admin", note: "" },
      { path: "U07 actor System", note: "" },
      { path: "U08 Guest --> (Xem chiến dịch)", note: "" },
      { path: "U09 Guest --> (Đăng ký)", note: "" },
      { path: "U10 Guest --> (Ủng hộ không quà)", note: "chỉ cần Gmail" },
      { path: "U11 Backer --> (Đặt Reward)", note: "phải đăng nhập" },
      { path: "U12 Backer --> (Kho đồ)", note: "" },
      { path: "U13 Backer --> (Chat)", note: "" },
      { path: "U14 Creator --> (KYC / KYB)", note: "" },
      { path: "U15 Creator --> (Quản lý campaign)", note: "" },
      { path: "U16 Creator --> (Giao hàng)", note: "" },
      { path: "U17 Admin --> (Duyệt)", note: "" },
      { path: "U18 Admin --> (Settle)", note: "" },
      { path: "U19 Admin --> (Khóa user)", note: "" },
      { path: "U20 System --> (Đối soát STK)", note: "" },
      { path: "U21 System --> (Chứng từ và Kho đồ)", note: "" },
      { path: "U22 @enduml", note: "" },
    ],
  },
  {
    kicker: "Use Case",
    title: "Nhóm Use Case",
    cards: [
      { title: "A. Tài khoản", body: "Đăng ký khi đặt quà. Ủng hộ không quà: khách chỉ Gmail; đã login thì Gmail và Kho đồ. Nâng CREATOR, khóa BANNED." },
      { title: "B. Gây quỹ", body: "CRUD campaign và reward, AoN hoặc KIA, cập nhật, blog chờ duyệt." },
      { title: "C. Dòng tiền", body: "Bốn kênh trên màn, đơn BANK_ESCROW, tip, COD chỉ khi gói cho phép, settle STK, chi, hoàn." },
      { title: "D. Kiểm duyệt", body: "KYC, eKYC tắt được, KYB, hàng đợi campaign và blog, report." },
    ],
  },
  {
    kicker: "Đặc tả",
    title: "Đặc tả UC-01 Tạo pledge",
    table: {
      headers: ["Mục", "Nội dung"],
      rows: [
        ["Actor chính", "Guest khi không quà. Backer khi có quà."],
        ["Actor phụ", "System, Admin đối soát STK trung gian"],
        ["Tiền điều kiện", "Không quà: Gmail hợp lệ, không bắt đăng nhập. Có quà: phải có session để nhập địa chỉ hoặc nhận Kho đồ. Campaign ACTIVE. Còn hạn. Còn suất."],
        ["Hậu điều kiện", "SUCCESS cộng tiền. Khách không quà: TT-UH gửi Gmail. Đã login không quà: Gmail và Kho đồ. Có quà: INV- và Kho đồ."],
        ["Luồng chính", "Chọn không quà hoặc gói → nhập Gmail hoặc đăng nhập → PENDING BANK_ESCROW → chuyển khoản → settle SUCCESS → khách nhận mail; đã login nhận mail và Kho đồ."],
        ["Ngoại lệ", "Hết hạn. Hết suất. Thiếu email. Có quà mà chưa login thì 401. paymentMethodId bị 400."],
      ],
    },
  },
  {
    kicker: "Đặc tả",
    title: "Đặc tả UC-02 Tạo và duyệt campaign",
    table: {
      headers: ["Mục", "Nội dung"],
      rows: [
        ["Actor chính", "Creator"],
        ["Actor phụ", "Admin"],
        ["Tiền điều kiện", "kyc_info VERIFIED. Cá nhân có CCCD. Tổ chức có MST/GPKD đã duyệt."],
        ["Hậu điều kiện", "ACTIVE thì nhận pledge. REJECTED thì có lý do và không public."],
        ["Luồng chính", "DRAFT → submit PENDING_REVIEW → Admin approve ACTIVE."],
        ["Ngoại lệ", "Thiếu ảnh. Goal không lớn hơn 0. Chưa KYC. Lý do từ chối để trống."],
      ],
    },
  },
  {
    kicker: "Activity",
    title: "Activity — thanh toán đến chứng từ",
    figures: [
      {
        key: "activity-checkout.png",
        alt: "Activity checkout đến chứng từ",
        caption: "",
      },
    ],
    steps: [
      { n: "01", t: "PENDING", d: "Không quà có thể chỉ Gmail. Có quà: đã đăng nhập. Chưa cộng currentAmount." },
      { n: "02", t: "Màn hình", d: "Ví, thẻ, NAPAS hoặc VietQR. API không nhận thẻ đã lưu. Mở trang chuyển khoản." },
      { n: "03", t: "Đối soát", d: "settlePledgeAsPaid cộng tiền một lần. Chưa đối soát thì không grant." },
      { n: "04", t: "Chứng từ", d: "Khách: TT-UH gửi Gmail. Đã login: Gmail và Kho đồ. Quà số: biên lai và Kho đồ." },
      { n: "05", t: "Reward", d: "Giao trong hạn, nhận đủ, chiến dịch chốt, chi trừ 8%." },
      { n: "06", t: "Hoàn", d: "Trễ SLA hoặc hụt goal kiểu AoN thì hoàn và revoke." },
    ],
  },
  {
    kicker: "ERD",
    title: "ERD — vòng gây quỹ lai",
    schema: [
      { title: "Định danh", items: ["users 1—1 kyc_info", "role ADMIN | BACKER | CREATOR_PENDING | CREATOR", "isOrganization, isAdmin"] },
      { title: "Gây quỹ", items: ["users 1—n projects 1—n campaigns", "campaigns 1—n rewards", "type REWARD hoặc DONATION", "fundingModel AoN | KIA"] },
      { title: "Dòng tiền", items: ["campaigns 1—n pledges", "pledges 1—1 certificates (TT-UH)", "pledges 1—1 invoices (INV-)", "pledges 1—n reward_digital_assets"] },
      { title: "Kiểm duyệt", items: ["campaign_reports", "audit_logs", "blacklist", "blog rejectionReason"] },
    ],
  },
  {
    kicker: "Schema",
    title: "Quan hệ và script Prisma",
    body: "Khóa đúng schema đang chạy. Không thêm bảng Kho đồ riêng — quà nằm reward_digital_assets.",
    table: {
      headers: ["Từ", "Đến", "Loại"],
      rows: [
        ["users", "campaigns", "1—n creatorId"],
        ["users", "pledges", "1—n userId. Null chỉ với đơn không quà."],
        ["campaigns", "pledges", "1—n"],
        ["pledges", "donation_certificates", "1—1 mã TT-UH"],
        ["pledges", "backer_invoices", "1—1 mã INV-"],
        ["users", "kyc_info", "1—1"],
      ],
    },
    tree: [
      { path: "model users", note: "role UserRole · isOrganization · isAdmin" },
      { path: "model kyc_info", note: "selfieImage · consentAt · ekycMeta · rejectedReason" },
      { path: "model campaigns", note: "feeRate mặc định 0.08 · fundingModel · status" },
      { path: "enum UserRole", note: "ADMIN BACKER CREATOR_PENDING CREATOR" },
      { path: "enum CampaignStatus", note: "DRAFT PENDING_REVIEW ACTIVE SUCCESS FAILED CANCELED" },
    ],
  },
  {
    kicker: "Module",
    title: "Module theo file đang chạy",
    tree: [
      { path: "src/lib/kyc.ts", note: "nộp và duyệt KYC" },
      { path: "src/lib/ekyc/cccd-qr.ts", note: "QR CCCD, chỉ điền form" },
      { path: "src/lib/platform-settings.ts", note: "ekyc_enabled, không sửa schema.prisma" },
      { path: "src/lib/digital-warehouse.ts", note: "grant và revoke Kho đồ" },
      { path: "src/lib/ship-sla.ts", note: "hạn giao + 2 ngày" },
      { path: "src/lib/money-buckets.ts", note: "giữ, chi, hoàn" },
      { path: "src/lib/redis.ts", note: "cache 300s, fail-open" },
      { path: "src/lib/payment/create-pledge.ts", note: "không quà: Gmail. có quà: session. BANK_ESCROW" },
    ],
  },
  {
    kicker: "Chức năng",
    title: "Thẻ chức năng — story ra màn hình",
    body: "Catalog để chiếu user story với route. Không phải danh sách mọi file.",
    table: {
      headers: ["Story", "Chức năng", "Màn hoặc API"],
      rows: [
        ["US-G01", "Xem chiến dịch public", "/projects · GET /api/campaigns"],
        ["US-G03", "Ủng hộ không quà bằng Gmail", "guestEmail · TT-UH chỉ gửi mail"],
        ["US-G02", "Đăng ký để đặt quà", "NextAuth · role BACKER"],
        ["US-B02", "Kho đồ sau khi login", "/purchases · grantDigitalWarehouseItem"],
        ["US-B04", "Tip", "0/5/10/15 và slider · ẩn nếu hàng sẵn hoặc COD"],
        ["US-C01", "KYC cá nhân", "/kyc · /upgrade/individual"],
        ["US-C06", "KYB tổ chức", "/kyc/to-chuc · isOrganization"],
        ["US-C05", "Cập nhật và blog", "/blog/my-posts · hàng đợi admin"],
        ["US-A01", "Bật tắt eKYC", "/dashboard/admin/system"],
        ["US-A02", "Settle TT-UH", "admin settle BANK_ESCROW"],
        ["US-A03", "Từ chối blog", "/dashboard/admin/blog · rejectionReason"],
        ["US-S03", "Cache", "Redis TTL 300s · xóa khi tạo campaign"],
      ],
    },
  },
  {
    kicker: "Test",
    title: "PCA, Test Plan, TR/TC",
    body: "Baseline PRD 07/09/2026. Test lead: Nguyễn Quách Phú Tài. Không đưa Web3, chatbot, PayPal vào P0.",
    table: {
      headers: ["TR", "Việc", "Kỳ vọng"],
      rows: [
        ["TR-01", "Donation khách / đã login", "Khách: chỉ Gmail. Đã login: Gmail và Kho đồ. Không COD."],
        ["TR-02", "Đặt quà chưa login", "API 401. Không tạo pledge."],
        ["TR-03", "Settle SUCCESS không quà", "Khách: mã TT-UH gửi email. Đã login: email và Kho đồ."],
        ["TR-04", "Hoàn Reward", "Revoke Kho đồ. Sao kê còn dòng hoàn."],
        ["TR-05", "Tắt eKYC", "Form tay. API eKYC 403."],
        ["TR-06", "Chưa KYC", "Campaign không ACTIVE."],
        ["TR-07", "Reject không lý do", "Không ghi REJECTED."],
        ["TR-08", "Redis chết", "Trang campaign vẫn đọc DB."],
      ],
    },
    bullets: [
      "Biên bản test phải ghi ngày, commit, môi trường. Không ghi 100% pass nếu chưa chạy lại.",
    ],
  },
  {
    kicker: "Deploy",
    title: "Database server và web server",
    cards: [
      { title: "Neon Postgres", body: "Sổ chính: users, KYC, campaigns, pledges, invoices, certificates, presentation. Biến DATABASE_URL." },
      { title: "Mongo và Redis", body: "Mongo cho chat. Redis chỉ cache campaigns và stats, TTL 300 giây, fail-open." },
      { title: "Vercel", body: "Next.js App Router. Demo platform-seven-navy-44.vercel.app. Checkout BANK_ESCROW, trang chuyển khoản STK trung gian." },
    ],
    steps: [
      { n: "01", t: "Build", d: "Push main. prisma generate. Không commit .env." },
      { n: "02", t: "Migrate", d: "Đồng bộ Neon với schema. Không dùng file schema placeholder." },
      { n: "03", t: "STK trung gian", d: "Khai tài khoản escrow. Checkout mở trang chuyển khoản, không cổng thanh toán ngoài." },
      { n: "04", t: "Smoke", d: "Một Guest Gmail không quà, một Reward có login, một reject có lý do." },
    ],
  },
  {
    kicker: "Chương 5",
    title: "Đánh giá đủ mục thầy",
    table: {
      headers: ["Mục", "Mức"],
      rows: [
        ["Khảo sát 6 mục và bài học 9 sàn", "Đủ trong phụ lục"],
        ["Bảng có cột Tử Tế Fund và vì sao", "Đủ"],
        ["Actor người, tổ chức, hệ thống kèm AC", "Đủ"],
        ["User story Guest, Backer, Creator, Admin, System", "Đủ, mỗi story 3 AC"],
        ["User flow 4 lane và nguồn PlantUML", "Đủ text. Ảnh UML xuất khi nộp Word"],
        ["Use case, đặc tả, activity", "Đủ UC-01 và UC-02"],
        ["ERD, schema, module, thẻ chức năng", "Đủ lõi đang chạy"],
        ["Test PCA đến TR/TC", "Khung đủ. Số pass phải chạy lại"],
        ["Deploy DB và web", "Neon, Mongo, Redis, Vercel"],
      ],
    },
    bullets: [
      "Slide kinh doanh phía trước không bị thay. Phụ lục này thay phụ lục cũ mỗi lần mở thuyết trình.",
    ],
  },
];
