import type { PresentationSlide } from "@/lib/admin-presentation-types";

export const ACADEMIC_SLIDES_2: PresentationSlide[] = [
  { kicker: "Actor", title: "Actor người — 1 người dùng", body: "Tách 1 người / 1 tổ chức / 1 hệ thống. Role thật: users.role.", table: { headers: ["Actor", "Role CSDL", "Hành động chính"], rows: [["Guest", "Chưa có users.id", "Xem campaign public, tìm kiếm, blog, bắt đầu checkout"], ["Backer", "BACKER", "Ủng hộ / đặt Reward, Kho đồ, chat, TT-UH / biên lai"], ["Creator chờ", "CREATOR_PENDING", "Nộp KYC/KYB, chưa public gọi vốn"], ["Creator", "CREATOR", "Project/campaign/reward, sao kê, fulfillment"], ["Admin", "ADMIN + isAdmin", "Duyệt KYC/campaign/blog, settle, tắt eKYC"]] } },
  { kicker: "Actor", title: "Actor tổ chức và hệ thống", body: "Tổ chức = users.isOrganization. Hệ thống = cổng + job nội bộ.", cards: [{ title: "Creator DN / HKD", body: "Cùng role CREATOR + GPKD/MST/eKYB. Xuất biên lai với tư cách người bán." }, { title: "Backer tổ chức CSR", body: "Donation để tên công ty trên TT-UH. Không nhận cổ phần." }], table: { headers: ["Hệ thống", "Làm", "Không làm"], rows: [["PayOS / VietQR / SePay / MoMo", "QR + webhook SUCCESS/FAILED", "Không tự chi hộ creator"], ["Neon Postgres", "User, campaign, pledge, invoice, KYC", "Không lưu ảnh gốc dài hạn"], ["MongoDB Atlas", "Chat / nội dung linh hoạt", "Không giữ sổ tiền"], ["Redis Cloud", "Cache campaigns/stats TTL 300s", "Không session, không lock payout"], ["Cloudinary", "Ảnh campaign / CCCD", "Không quyết định KYC"], ["Webhook / cron", "Đổi trạng thái, grant/revoke Kho đồ", "Tiền nằm STK trung gian"]] } },
  { kicker: "Actor", title: "Bảng hành động theo actor", table: { headers: ["Actor", "Được phép", "Bị chặn khi"], rows: [["Guest", "Listing, chi tiết public", "Không dashboard creator / sao kê"], ["Backer", "Pledge, chat, Kho đồ, report", "Không sửa campaign người khác"], ["Creator", "CRUD draft, fulfillment", "Chưa VERIFIED thì không ACTIVE"], ["Admin", "Approve KYC/campaign/blog; settle; khóa user", "Không giả lập webhook từ UI thường"], ["System", "Đối soát, chứng từ, grant/revoke", "Fail-open cache"]] } },
  { kicker: "User Story", title: "User Story — Backer", body: "As a [Role] – I want [Goal] – So that [Benefit].", table: { headers: ["ID", "User Story", "Ghi chú"], rows: [["US-B01", "As a Backer, I want ủng hộ không quà bằng VietQR, so that có TT-UH sau admin settle SUCCESS.", "NO_GIFT; luôn ONLINE"], ["US-B02", "As a Backer, I want đặt Reward và xem Kho đồ, so that biết hàng đã vào hay chờ SLA.", "grantDigitalWarehouseItem"], ["US-B03", "As a Backer, I want hoàn nếu trễ SLA, so that tiền không kẹt.", "ship-sla = hạn + 2 ngày"], ["US-B04", "As a Guest, I want xem campaign và lịch sử creator trước khi đăng nhập, so that quyết định có ủng hộ.", "/projects"]] } },
  { kicker: "User Story", title: "User Story — Creator và Admin", table: { headers: ["ID", "User Story", "Ghi chú"], rows: [["US-C01", "As a Creator, I want nộp CCCD (± GPKD) rồi chờ duyệt, so that mở chiến dịch.", "/kyc"], ["US-C02", "As a Creator, I want một campaign vừa ủng hộ vừa pre-order, so that không tách hai trang.", "REWARD|DONATION"], ["US-C03", "As a Creator, I want sao kê không xóa lịch sử, so that đối soát STK trung gian.", "dòng đỏ = hoàn"], ["US-A01", "As an Admin, I want bật/tắt eKYC, so that khi API lỗi vẫn nhận hồ sơ tay.", "ekyc_enabled"], ["US-A02", "As an Admin, I want settle BANK_ESCROW, so that TT-UH chỉ ra khi tiền đã chốt.", "settle SUCCESS"], ["US-S01", "As the System, I want ghi Kho đồ khi webhook SUCCESS, so that backer thấy quà ngay.", "digital-warehouse.ts"]] } },
  { kicker: "AC", title: "Acceptance Criteria", body: "AC viết để test được.", blocks: [{ heading: "US-B01 — không quà", bullets: ["Given Donation/no-gift ACTIVE, When checkout, Then không có radio COD.", "Given chờ settle, When /purchases, Then thẻ chờ — chưa TT-UH.", "Given admin settle SUCCESS, Then có mã TT-UH + notify/email.", "Given webhook chưa SUCCESS, Then không chứng từ, không asset."] }, { heading: "US-C01 — KYC", bullets: ["Given eKYC ON, When thiếu ảnh CCCD, Then API từ chối.", "Given QR mặt sau, When đọc được, Then chỉ fill form — không gọi CSDL QG.", "Given PENDING, Then campaign không ACTIVE.", "Given reject, Then REJECTED + rejectedReason."] }] }
];
