import type { PresentationSlide } from "@/lib/admin-presentation-types";

export const ACADEMIC_SLIDES_4: PresentationSlide[] = [
  {
    kicker: "User Flow",
    title: "User Flow — 4 lane",
    body: "Bốn lane đọc trên slide. Nguồn PlantUML ở slide sau, dán vào plantuml.com khi nộp báo cáo Word.",
    lanes: [
      {
        title: "Guest → Backer",
        tone: "emerald",
        steps: [
          "Xem /projects chỉ campaign ACTIVE.",
          "Đăng ký NextAuth, role BACKER.",
          "Chọn không quà hoặc gói Reward. Không quà thì chỉ ONLINE.",
          "Tip nếu gói không phải hàng sẵn và không phải COD.",
          "Pledge PENDING, quét VietQR.",
          "SUCCESS: Reward vào /purchases. Donation thành thẻ chờ TT-UH.",
          "Trễ SLA: hoàn đơn đó, Kho đồ mất quà.",
        ],
      },
      {
        title: "Creator",
        tone: "navy",
        steps: [
          "Nộp CCCD hoặc GPKD/MST. QR chỉ điền form.",
          "Chờ VERIFIED. Reject thì có lý do, không public.",
          "Tạo project + campaign DRAFT, goal > 0.",
          "Gửi PENDING_REVIEW. Admin cho ACTIVE.",
          "Cập nhật CAMPAIGN_UPDATE nếu đã VERIFIED.",
          "Xác nhận giao hoặc nhận tại chỗ trong hạn.",
          "Xem sao kê. Không xóa dòng.",
        ],
      },
      {
        title: "Admin",
        tone: "rose",
        steps: [
          "Hàng đợi KYC, campaign, blog.",
          "Duyệt hoặc từ chối. Từ chối bắt buộc lý do.",
          "Tắt eKYC khi cần: form tay, API eKYC 403.",
          "Settle BANK_ESCROW SUCCESS thì mới có TT-UH.",
          "Khóa user. Pledge cũ và chứng từ không bị xóa.",
        ],
      },
      {
        title: "System + cổng thanh toán",
        tone: "default",
        steps: [
          "Tạo QR. Tiền vào STK trung gian, chưa về creator.",
          "Webhook SUCCESS cộng tiền một lần. FAILED thì dừng.",
          "Có quà thì grant Kho đồ. Không quà thì không cấp giấy ở bước này.",
          "Redis cache 300 giây, lỗi thì đọc DB.",
          "Đủ điều kiện chi: chiến dịch đã chốt, đơn đã nhận đủ, trừ 8% rồi chi.",
        ],
      },
    ],
  },
  {
    kicker: "User Flow",
    title: "PlantUML — Guest/Backer và Creator/Admin",
    body: "Hai sơ đồ. Mỗi dòng là một câu PlantUML. Chép cả khối vào plantuml.com để ra ảnh nộp Word. Slide web không vẽ UML.",
    tree: [
      { path: "A01 @startuml guest-backer", note: "" },
      { path: "A02 actor Guest", note: "" },
      { path: "A03 actor Backer", note: "" },
      { path: "A04 actor Admin", note: "" },
      { path: "A05 participant App", note: "" },
      { path: "A06 participant Cong as Cổng", note: "PayOS / SePay / MoMo" },
      { path: "A07 database DB", note: "Neon" },
      { path: "A08 Guest -> App : xem /projects", note: "chỉ ACTIVE" },
      { path: "A09 Guest -> App : NextAuth", note: "role BACKER" },
      { path: "A10 Backer -> App : gói hoặc không quà", note: "không quà = ONLINE" },
      { path: "A11 App -> DB : pledges PENDING", note: "chưa cộng tiền" },
      { path: "A12 App -> Cong : VietQR", note: "" },
      { path: "A13 Cong --> App : SUCCESS hoặc FAILED", note: "" },
      { path: "A14 alt Reward và SUCCESS", note: "" },
      { path: "A15 App -> DB : grant /purchases", note: "" },
      { path: "A16 else Donation và SUCCESS", note: "" },
      { path: "A17 App -> DB : thẻ chờ", note: "chưa TT-UH" },
      { path: "A18 Admin -> App : settle SUCCESS", note: "" },
      { path: "A19 App -> DB : cấp TT-UH", note: "" },
      { path: "A20 else FAILED", note: "" },
      { path: "A21 App -> DB : không cộng, không grant", note: "" },
      { path: "A22 end", note: "" },
      { path: "A23 @enduml", note: "" },
      { path: "B01 @startuml creator-admin", note: "" },
      { path: "B02 actor Creator", note: "" },
      { path: "B03 actor Admin", note: "" },
      { path: "B04 participant App", note: "" },
      { path: "B05 database DB", note: "" },
      { path: "B06 Creator -> App : /kyc CCCD hoặc MST", note: "QR chỉ điền form" },
      { path: "B07 App -> DB : kyc PENDING", note: "" },
      { path: "B08 Admin -> App : VERIFIED hoặc REJECTED", note: "reject có lý do" },
      { path: "B09 Creator -> App : campaign DRAFT", note: "goal > 0" },
      { path: "B10 Creator -> App : submit", note: "PENDING_REVIEW" },
      { path: "B11 Admin -> App : ACTIVE", note: "trước đó không nhận tiền" },
      { path: "B12 @enduml", note: "" },
    ],
  },
];
