import type { PresentationSlide } from "@/lib/admin-presentation-types";

export const ACADEMIC_SLIDES_4: PresentationSlide[] = [
  {
    kicker: "Chức năng",
    title: "Thẻ chức năng — story ra màn hình",
    body: "Đặt ngay sau user story. Catalog để chiếu việc user nói với route đang chạy, không phải danh sách mọi file.",
    table: {
      headers: ["Story", "Chức năng", "Màn hoặc API", "Trạng thái"],
      rows: [
        ["US-G01", "Xem chiến dịch public", "/projects · GET /api/campaigns", "Đang chạy"],
        ["US-G02", "Đăng ký để đặt quà", "NextAuth · role BACKER", "Đang chạy"],
        ["US-G03", "Ủng hộ không quà bằng Gmail", "guestEmail · TT-UH chỉ gửi mail", "Đang chạy"],
        ["US-G04", "Đọc blog đã xuất bản", "/blog · ẩn PENDING_REVIEW", "Đang chạy"],
        ["US-B01", "Ủng hộ đã login", "PledgeForm · Kho đồ /purchases", "Đang chạy"],
        ["US-B02", "Đặt Reward", "bắt session · grantDigitalWarehouseItem", "Đang chạy"],
        ["US-B04", "Tip", "0/5/10/15 và slider · ẩn nếu hàng sẵn hoặc COD", "Đang chạy"],
        ["US-B05", "Chat", "thread · Mongo · 4 kết quả cuộc gọi", "Đang chạy"],
        ["US-B06", "Báo cáo campaign", "report gắn campaign · không tự ẩn", "Đang chạy"],
        ["US-C01", "KYC cá nhân", "/kyc · /upgrade/individual", "Đang chạy"],
        ["US-C06", "KYB tổ chức", "/kyc/to-chuc · isOrganization", "Đang chạy"],
        ["US-C05", "Cập nhật và blog", "/blog/my-posts · /dashboard/admin/blog", "Đang chạy"],
        ["US-C08", "Hồ sơ công khai", "/profile · Lưu nháp rồi Xuất bản", "Đang chạy"],
        ["US-A01", "Bật tắt eKYC", "/dashboard/admin/system", "Đang chạy"],
        ["US-A02", "Settle TT-UH", "admin settle BANK_ESCROW", "Đang chạy"],
        ["US-A03", "Từ chối blog", "rejectionReason · reviewedAt · reviewedBy", "Đang chạy"],
        ["US-S03", "Cache", "Redis TTL 300s · xóa khi tạo campaign", "Đang chạy"],
        ["US-C03", "Xuất sao kê Excel", "Chưa có nút xuất file", "Chưa làm P0"],
        ["US-C07", "Nhân bản campaign", "Chưa có clone listing", "Chưa làm P0"],
        ["—", "Tài khoản nhân viên / admin phụ", "Một tổ chức là một users.id", "Chưa làm P0"],
      ],
    },
  },
  {
    kicker: "Chức năng",
    title: "Nhóm màn hình đang chạy",
    cards: [
      { title: "A. Tài khoản", body: "Đăng ký, đăng nhập NextAuth. Nâng creator ở /kyc và /upgrade/individual. Tổ chức ở /kyc/to-chuc. Khóa BANNED không tạo pledge mới." },
      { title: "B. Gây quỹ", body: "Tạo project và campaign DRAFT, gói Reward, AoN hoặc KIA, gửi PENDING_REVIEW. Cập nhật CAMPAIGN_UPDATE nếu đã VERIFIED. Blog loại khác chờ duyệt." },
      { title: "C. Dòng tiền", body: "Bốn kênh trên màn. Đơn BANK_ESCROW, trang chuyển khoản. Tip. COD chỉ khi gói cho phép. Settle, chi trừ 8%, hoàn từng đơn." },
      { title: "D. Kiểm duyệt", body: "Hàng đợi KYC, campaign, blog. eKYC tắt được. Report không tự ẩn campaign. Audit khi admin khóa hoặc duyệt." },
    ],
    bullets: [
      "Checkout không trừ ví hay thẻ đã liên kết. API trả trang chuyển khoản STK trung gian.",
      "Kho đồ là /purchases, không có bảng mới. Quà nằm reward_digital_assets.",
    ],
  },
  {
    kicker: "User Flow",
    title: "User Flow — 4 lane đọc được",
    body: "Bốn lane chiếu trên slide. Ảnh Guest/Backer và Creator/Admin ở slide sau. Nguồn PlantUML nộp trong Word, không chiếu mã.",
    lanes: [
      {
        title: "Guest → Backer",
        tone: "emerald",
        steps: [
          "Xem /projects chỉ campaign ACTIVE.",
          "Không quà + khách: chỉ cần Gmail. Giấy TT-UH gửi về mail. Không vào Kho đồ.",
          "Có quà: phải đăng nhập để nhập địa chỉ hoặc nhận Kho đồ.",
          "Tip nếu gói không phải hàng sẵn và không phải COD.",
          "Màn bốn kênh. Pledge PENDING, trang chuyển khoản STK trung gian.",
          "settle SUCCESS: khách nhận TT-UH qua Gmail; đã login nhận Gmail và Kho đồ.",
          "Trễ SLA: hoàn đơn đó, Kho đồ mất quà.",
        ],
      },
      {
        title: "Creator",
        tone: "navy",
        steps: [
          "Nộp CCCD hoặc GPKD/MST. QR chỉ điền form.",
          "Chờ VERIFIED. Reject thì có lý do, sửa rồi gửi lại.",
          "Tạo project + campaign DRAFT, goal > 0.",
          "Gửi PENDING_REVIEW. Admin cho ACTIVE.",
          "Cập nhật CAMPAIGN_UPDATE nếu đã VERIFIED.",
          "Xác nhận giao hoặc nhận tại chỗ trong hạn.",
          "Xem sao kê. Không xóa dòng.",
        ],
      },
      {
        title: "Admin",
        tone: "rose",
        steps: [
          "Hàng đợi KYC, campaign, blog.",
          "Duyệt hoặc từ chối. Từ chối bắt buộc lý do.",
          "Tắt eKYC khi cần: form tay, API eKYC 403.",
          "Settle BANK_ESCROW SUCCESS thì mới có TT-UH.",
          "Khóa user. Pledge cũ và chứng từ không bị xóa.",
        ],
      },
      {
        title: "System + STK trung gian",
        tone: "default",
        steps: [
          "API trả BANK_ESCROW. Không trừ ví hay thẻ đã liên kết.",
          "PENDING thì dừng, không cộng currentAmount.",
          "settlePledgeAsPaid cộng tiền một lần.",
          "Khách: TT-UH về Gmail. Đã login: Gmail và Kho đồ.",
          "Redis cache 300 giây, lỗi thì đọc DB.",
          "Đủ điều kiện chi: chiến dịch đã chốt, đơn đã nhận đủ, trừ 8%.",
        ],
      },
    ],
  },
  {
    kicker: "User Flow",
    title: "Sơ đồ Guest/Backer và Creator/Admin",
    figures: [
      { key: "flow-guest-backer.png", alt: "User flow Guest và Backer", caption: "Không quà chỉ Gmail. Có quà phải đăng nhập. Settle mới cấp giấy." },
      { key: "flow-creator-admin.png", alt: "User flow Creator và Admin", caption: "KYC rồi DRAFT rồi PENDING_REVIEW. ACTIVE mới nhận tiền." },
    ],
    steps: [
      { n: "01", t: "Guest", d: "Xem ACTIVE. Không quà nhập Gmail. Có quà thì dừng để đăng nhập." },
      { n: "02", t: "Backer", d: "Chọn gói, tip nếu được, nhận trang chuyển khoản." },
      { n: "03", t: "STK", d: "Tiền vào tài khoản trung gian. Pledge vẫn PENDING cho đến khi admin settle." },
      { n: "04", t: "Creator", d: "CCCD hoặc MST. Campaign không public khi chưa VERIFIED và chưa ACTIVE." },
      { n: "05", t: "Admin", d: "Duyệt có lý do nếu từ chối. Settle không chạy từ tài khoản backer." },
    ],
    note: "Nguồn PlantUML nộp kèm báo cáo Word. Slide này không chiếu mã A01–B12.",
  },
  {
    kicker: "User Flow",
    title: "Luồng System — đối soát đến chứng từ",
    steps: [
      { n: "01", t: "Tạo đơn", d: "create-pledge ghi PENDING, method BANK_ESCROW. Có paymentMethodId thì 400." },
      { n: "02", t: "Chưa tiền", d: "currentAmount không tăng. Không TT-UH, không asset, không INV-." },
      { n: "03", t: "Settle", d: "settlePledgeAsPaid cộng tiền một lần. Lần hai không tạo thêm asset." },
      { n: "04", t: "Không quà", d: "Khách: mail TT-UH. Đã login: mail và Kho đồ." },
      { n: "05", t: "Có quà", d: "INV- và grant /purchases nếu quà số. Quà vật lý chờ giao." },
      { n: "06", t: "Chi hoặc hoàn", d: "Đủ hạn và đã chốt thì chi trừ 8%. Trễ SLA thì hoàn đơn đó và revoke." },
    ],
    bullets: [
      "Cache không nằm trên luồng tiền. Redis lỗi thì trang campaign vẫn đọc DB.",
      "Chat kết thúc không đổi trạng thái pledge.",
    ],
  },
];
