import type { PresentationSlide } from "@/lib/admin-presentation-types";

export const ACADEMIC_SLIDES_4: PresentationSlide[] = [
  {
    kicker: "User Flow",
    title: "User Flow — 4 lane",
    body: "Bốn lane đọc trên slide. Nguồn PlantUML ở slide sau, dán vào plantuml.com khi nộp báo cáo Word.",
    lanes: [
      {
        title: "Guest → Backer",
        tone: "emerald",
        steps: [
          "Xem /projects chỉ campaign ACTIVE.",
          "Không quà + khách: chỉ cần Gmail. Giấy TT-UH gửi về mail. Không vào Kho đồ.",
          "Có quà: phải đăng nhập để nhập địa chỉ hoặc nhận Kho đồ.",
          "Tip nếu gói không phải hàng sẵn và không phải COD.",
          "Màn bốn kênh. Pledge PENDING, trang chuyển khoản STK trung gian.",
          "settle SUCCESS: khách nhận TT-UH qua Gmail; đã login nhận Gmail và Kho đồ; quà số vào /purchases.",
          "Trễ SLA: hoàn đơn đó, Kho đồ mất quà.",
        ],
      },
      {
        title: "Creator",
        tone: "navy",
        steps: [
          "Nộp CCCD hoặc GPKD/MST. QR chỉ điền form.",
          "Chờ VERIFIED. Reject thì có lý do, không public.",
          "Tạo project + campaign DRAFT, goal > 0.",
          "Gửi PENDING_REVIEW. Admin cho ACTIVE.",
          "Cập nhật CAMPAIGN_UPDATE nếu đã VERIFIED.",
          "Xác nhận giao hoặc nhận tại chỗ trong hạn.",
          "Xem sao kê. Không xóa dòng.",
        ],
      },
      {
        title: "Admin",
        tone: "rose",
        steps: [
          "Hàng đợi KYC, campaign, blog.",
          "Duyệt hoặc từ chối. Từ chối bắt buộc lý do.",
          "Tắt eKYC khi cần: form tay, API eKYC 403.",
          "Settle BANK_ESCROW SUCCESS thì mới có TT-UH.",
          "Khóa user. Pledge cũ và chứng từ không bị xóa.",
        ],
      },
      {
        title: "System + STK trung gian",
        tone: "default",
        steps: [
          "API trả BANK_ESCROW. Không trừ ví hay thẻ đã liên kết.",
          "settlePledgeAsPaid cộng tiền một lần. PENDING thì dừng.",
          "Khách: TT-UH về Gmail. Đã login: Gmail và Kho đồ. Quà số: grant Kho đồ.",
          "Redis cache 300 giây, lỗi thì đọc DB.",
          "Đủ điều kiện chi: chiến dịch đã chốt, đơn đã nhận đủ, trừ 8% rồi chi.",
        ],
      },
    ],
  },
  {
    kicker: "User Flow",
    title: "Sơ đồ Guest/Backer và Creator/Admin",
    figures: [
      {
        key: "flow-guest-backer.png",
        alt: "User flow Guest và Backer",
        caption: "",
      },
      {
        key: "flow-creator-admin.png",
        alt: "User flow Creator và Admin",
        caption: "",
      },
    ],
    tree: [
      { path: "A01 @startuml guest-backer", note: "" },
      { path: "A02 actor Guest", note: "" },
      { path: "A03 actor Backer", note: "" },
      { path: "A04 actor Admin", note: "" },
      { path: "A05 participant App", note: "" },
      { path: "A06 participant STK as \"STK trung gian\"", note: "" },
      { path: "A07 database DB", note: "Neon" },
      { path: "A08 Guest -> App : xem /projects", note: "chỉ ACTIVE" },
      { path: "A09 alt không quà", note: "" },
      { path: "A10 Guest -> App : Gmail", note: "không cần đăng nhập" },
      { path: "A11 else có quà", note: "" },
      { path: "A12 Backer -> App : đăng nhập", note: "địa chỉ hoặc Kho đồ" },
      { path: "A13 end", note: "" },
      { path: "A14 App -> DB : pledges PENDING", note: "BANK_ESCROW" },
      { path: "A15 App --> Backer : /thanh-toan/chuyen-khoan", note: "" },
      { path: "A16 Backer -> STK : chuyển khoản", note: "" },
      { path: "A17 Admin -> App : settlePledgeAsPaid", note: "" },
      { path: "A18 alt không quà", note: "" },
      { path: "A19 App -> Guest : TT-UH qua Gmail", note: "không Kho đồ" },
      { path: "A20 else đã login", note: "Gmail và Kho đồ" },
      { path: "A21 App -> DB : grant /purchases", note: "" },
      { path: "A22 end", note: "" },
      { path: "A23 @enduml", note: "" },
      { path: "B01 @startuml creator-admin", note: "" },
      { path: "B02 actor Creator", note: "" },
      { path: "B03 actor Admin", note: "" },
      { path: "B04 participant App", note: "" },
      { path: "B05 database DB", note: "" },
      { path: "B06 Creator -> App : /kyc CCCD hoặc MST", note: "QR chỉ điền form" },
      { path: "B07 App -> DB : kyc PENDING", note: "" },
      { path: "B08 Admin -> App : VERIFIED hoặc REJECTED", note: "reject có lý do" },
      { path: "B09 Creator -> App : campaign DRAFT", note: "goal > 0" },
      { path: "B10 Creator -> App : submit", note: "PENDING_REVIEW" },
      { path: "B11 Admin -> App : ACTIVE", note: "trước đó không nhận tiền" },
      { path: "B12 @enduml", note: "" },
    ],
  },
];
