import type { PresentationSlide } from "@/lib/admin-presentation-types";

export const ACADEMIC_SLIDES_3: PresentationSlide[] = [
  { kicker: "User Flow", title: "User Flow — Creator gọi vốn (PlantUML)", body: "Guest → đăng ký → KYC → tạo campaign → Admin duyệt → public.", tree: [{ path: "01 @startuml creator-onboard", note: "" }, { path: "02 Guest -> App: NextAuth", note: "role BACKER" }, { path: "03 Backer -> App: /kyc", note: "CCCD ± GPKD" }, { path: "04 App -> DB: kyc_info PENDING", note: "" }, { path: "05 Admin -> App: VERIFIED | REJECTED", note: "" }, { path: "06 Creator -> App: Project + Campaign DRAFT", note: "" }, { path: "07 Admin -> App: ACTIVE", note: "mới nhận pledge" }, { path: "08 @enduml", note: "" }] },
  { kicker: "User Flow", title: "User Flow — Backer ủng hộ / đặt hàng (PlantUML)", tree: [{ path: "01 @startuml pledge-money", note: "" }, { path: "02 Backer -> App: chọn gói / không quà + tip", note: "" }, { path: "03 App -> DB: pledges PENDING", note: "chưa cộng currentAmount" }, { path: "04 App -> Cổng: VietQR / PayOS / MoMo", note: "" }, { path: "05 Cổng -> App: webhook SUCCESS | FAILED", note: "" }, { path: "06 App -> Kho đồ: grant nếu Reward", note: "" }, { path: "07 App -> Admin: settle nếu Donation", note: "BANK_ESCROW" }, { path: "08 Creator -> App: gửi / nhận tại chỗ", note: "SLA + 2 ngày" }, { path: "09 App -> Bank: payout đủ điều kiện", note: "trừ 8%" }, { path: "10 @enduml", note: "" }] },
  { kicker: "Use Case", title: "Use Case Diagram (PlantUML)", tree: [{ path: "01 @startuml uc-tute", note: "" }, { path: "02 actor Guest / Backer / Creator / Admin / System", note: "" }, { path: "03 Guest --> (Xem chiến dịch) (Đăng ký)", note: "" }, { path: "04 Backer --> (Ủng hộ) (Đặt Reward) (Kho đồ) (Chat)", note: "" }, { path: "05 Creator --> (KYC) (Quản lý campaign) (Fulfillment)", note: "" }, { path: "06 Admin --> (Duyệt) (Settle) (Khóa user)", note: "" }, { path: "07 System --> (Webhook) (Chứng từ + Kho đồ)", note: "" }, { path: "08 @enduml", note: "" }] },
  { kicker: "Use Case", title: "Nhóm Use Case", cards: [{ title: "A. Tài khoản", body: "Đăng ký, NextAuth 5, nâng CREATOR, BANNED." }, { title: "B. Gây quỹ", body: "CRUD campaign/reward, AoN/KIA, follow, update." }, { title: "C. Dòng tiền", body: "Checkout, webhook, tip, COD reward, settle, payout, refund." }, { title: "D. Kiểm duyệt", body: "KYC/eKYC, eKYB, hàng đợi campaign/blog, report." }] },
  { kicker: "Đặc tả", title: "Đặc tả UC-01 Tạo pledge", table: { headers: ["Mục", "Nội dung"], rows: [["Actor chính", "Backer"], ["Actor phụ", "System, cổng, Admin settle Donation"], ["Tiền điều kiện", "Campaign ACTIVE; còn hạn; còn suất"], ["Hậu điều kiện", "SUCCESS sau webhook; Kho đồ hoặc thẻ chờ TT-UH"], ["Luồng chính", "Chọn gói → tip → PENDING → QR → SUCCESS → đầu ra"], ["Ngoại lệ", "Hết hạn; hết suất; BANNED; timeout cổng"]] } },
  { kicker: "Đặc tả", title: "Đặc tả UC-02 Tạo và duyệt campaign", table: { headers: ["Mục", "Nội dung"], rows: [["Actor chính", "Creator"], ["Tiền điều kiện", "kyc_info VERIFIED"], ["Hậu điều kiện", "ACTIVE hoặc REJECT + lý do"], ["Luồng chính", "DRAFT → submit PENDING_REVIEW → Admin approve"], ["Ngoại lệ", "Thiếu ảnh; goal <= 0; chưa KYC"]] } },
  { kicker: "Activity", title: "Activity — thanh toán đến chứng từ", steps: [{ n: "01", t: "PENDING", d: "Insert pledge. Chưa cộng currentAmount." }, { n: "02", t: "Cổng", d: "QR / ví. Timeout → FAILED." }, { n: "03", t: "SUCCESS", d: "Cộng tiền. Grant Kho đồ nếu có quà." }, { n: "04", t: "Donation", d: "Thẻ chờ. Admin settle → TT-UH." }, { n: "05", t: "Reward", d: "Fulfillment + chốt → payout trừ 8%." }, { n: "06", t: "Hoàn", d: "Trễ SLA / miss AoN → refund + revoke." }] },
  { kicker: "ERD", title: "ERD — vòng gây quỹ lai", schema: [{ title: "Định danh", items: ["users 1—1 kyc_info", "role ADMIN|BACKER|CREATOR_PENDING|CREATOR", "isOrganization"] }, { title: "Gây quỹ", items: ["users 1—n projects 1—n campaigns", "campaigns 1—n rewards", "type REWARD|DONATION", "fundingModel AoN|KIA"] }, { title: "Dòng tiền", items: ["campaigns 1—n pledges", "pledges 1—1 certificates / invoices", "pledges 1—n reward_digital_assets"] }, { title: "Kiểm duyệt", items: ["campaign_reports", "audit_logs", "blacklist"] }] },
  { kicker: "Schema", title: "Quan hệ + script Prisma", table: { headers: ["Từ", "Đến", "Loại"], rows: [["users", "campaigns", "1—n creatorId"], ["users", "pledges", "1—n userId?"], ["campaigns", "pledges", "1—n"], ["pledges", "donation_certificates", "1—1 TT-UH"], ["pledges", "backer_invoices", "1—1 INV-"], ["users", "kyc_info", "1—1"]] }, tree: [{ path: "model users", note: "role UserRole · isOrganization · isAdmin" }, { path: "model kyc_info", note: "selfieImage · consentAt · ekycMeta" }, { path: "model campaigns", note: "feeRate @default(0.08) · fundingModel" }, { path: "enum UserRole", note: "ADMIN BACKER CREATOR_PENDING CREATOR" }, { path: "enum CampaignStatus", note: "DRAFT PENDING_REVIEW ACTIVE SUCCESS FAILED CANCELED" }] },
  { kicker: "Module", title: "Module / function", tree: [{ path: "src/lib/kyc.ts", note: "nộp / duyệt; toggle eKYC" }, { path: "src/lib/ekyc/cccd-qr.ts", note: "QR CCCD, chỉ fill form" }, { path: "src/lib/digital-warehouse.ts", note: "grant / revoke Kho đồ" }, { path: "src/lib/ship-sla.ts", note: "hạn + 2 ngày" }, { path: "src/lib/money-buckets.ts", note: "giữ / chi / hoàn" }, { path: "src/app/api/webhooks/*", note: "PayOS / SePay / MoMo" }, { path: "src/lib/admin-presentation.ts", note: "seed slide + version" }] },
  { kicker: "Test", title: "PCA, Test Plan, TR/TC", body: "Baseline PRD 07/09/2026. Lead: Nguyễn Quách Phú Tài. Không P0: Web3, chatbot, PayPal.", table: { headers: ["TR", "Yêu cầu", "Kỳ vọng"], rows: [["TR-01", "Donation ẩn COD", "method ONLINE"], ["TR-02", "Webhook FAILED", "không cộng tiền, không grant"], ["TR-03", "Settle SUCCESS", "có TT-UH"], ["TR-04", "Refund Reward", "revoke Kho đồ"], ["TR-05", "eKYC off", "form tay; API eKYC 403"], ["TR-06", "Chưa KYC", "không ACTIVE"]] }, bullets: ["Report phải ghi ngày, commit, môi trường. Không ghi 100% pass nếu chưa rerun."] },
  { kicker: "Deploy", title: "DATABASE SERVER + WEB SERVER", cards: [{ title: "Neon Postgres", body: "Sổ đúng: users, kyc, campaigns, pledges, invoices, certificates, presentation_deck. DATABASE_URL." }, { title: "Mongo + Redis", body: "Mongo chat. Redis cache campaigns/stats TTL 300s, fail-open." }, { title: "Vercel", body: "App Router. Demo platform-seven-navy-44.vercel.app. Webhook HTTPS. Bump seed version → slide mới." }], steps: [{ n: "01", t: "Build", d: "Push main, prisma generate." }, { n: "02", t: "Migrate", d: "Đồng bộ Neon." }, { n: "03", t: "Webhook", d: "Khai báo URL production." }, { n: "04", t: "Smoke", d: "3 role + 1 donation + 1 reward." }] },
  { kicker: "Chương 5", title: "Đánh giá — list thầy", table: { headers: ["Mục", "Mức"], rows: [["Khảo sát + bức tranh lớn", "Đủ"], ["Actor người / tổ chức / hệ thống", "Đủ"], ["User Story + AC", "Đủ P0"], ["User Flow + UC + activity", "Đủ dạng text PlantUML"], ["ERD + schema + module", "Đủ lõi gây quỹ"], ["Test PCA→report", "Khung đủ; số liệu phải rerun"], ["Deploy DB + Web", "Neon / Mongo / Redis / Vercel"]] }, bullets: ["Slide 1–20: mô hình kinh doanh. Từ 21: phụ lục học thuật."] }
];
