import type { ViewId } from "./types";

export const COVERAGE: { group: string; code: string; name: string; view: ViewId }[] = [
  { group: "Danh mục", code: "MD01", name: "Hàng hóa, combo, thuế suất", view: "dm" },
  { group: "Danh mục", code: "MD02", name: "Đơn vị tính / quy đổi thùng–lẻ", view: "dm" },
  { group: "Danh mục", code: "MD03", name: "Khách, NCC, hạn mức công nợ", view: "dm" },
  { group: "Danh mục", code: "MD04", name: "Giá bán theo kênh", view: "pos" },
  { group: "Danh mục", code: "MD05", name: "Nhóm ngành HKD / chế độ thuế", view: "thue" },
  { group: "POS", code: "POS01", name: "Bán quầy + mã vạch", view: "pos" },
  { group: "POS", code: "POS02", name: "Giữ đơn, đổi trả", view: "pos" },
  { group: "POS", code: "POS03", name: "Tiền mặt, QR, thẻ, điểm, ghi nợ", view: "pos" },
  { group: "POS", code: "POS04", name: "Mở ca / giao ca / sổ quỹ", view: "pos" },
  { group: "POS", code: "POS05", name: "Khuyến mại dòng hàng", view: "pos" },
  { group: "POS", code: "POS06", name: "Đặt cọc và bán chịu", view: "pos" },
  { group: "POS", code: "POS07", name: "Bill tạm tính", view: "pos" },
  { group: "F&B", code: "FB01", name: "Sơ đồ bàn / khu", view: "fnb" },
  { group: "F&B", code: "FB02", name: "Bếp / bar ticket", view: "fnb" },
  { group: "F&B", code: "FB03", name: "Giá vốn món", view: "fnb" },
  { group: "F&B", code: "FB04", name: "Gọi món tại bàn", view: "fnb" },
  { group: "F&B", code: "FB05", name: "Tính giờ phòng", view: "fnb" },
  { group: "Omni", code: "OM01", name: "Tồn đa kho / đa kênh", view: "kho" },
  { group: "Omni", code: "OM02", name: "Đơn Shopee, TikTok, web", view: "omni" },
  { group: "Omni", code: "OM03", name: "Vận đơn và COD", view: "omni" },
  { group: "Omni", code: "OM04", name: "Đơn livestream đưa vào sổ", view: "omni" },
  { group: "Omni", code: "OM05", name: "Kênh website Tử Tế", view: "omni" },
  { group: "Kho", code: "WH01", name: "Nhập, xuất, chuyển, kiểm kê", view: "kho" },
  { group: "Kho", code: "WH02", name: "Nhiều kho", view: "kho" },
  { group: "Kho", code: "WH03", name: "Lô, HSD, xuất FEFO", view: "kho" },
  { group: "Kho", code: "WH04", name: "Serial / IMEI", view: "pos" },
  { group: "Kho", code: "WH05", name: "Tồn vật lý", view: "kho" },
  { group: "Kho", code: "WH06", name: "Giá vốn bình quân", view: "so" },
  { group: "Kho", code: "WH07", name: "Cảnh báo tồn tối thiểu", view: "kho" },
  { group: "Kho", code: "WH08", name: "Đơn mua và nhận hàng", view: "mua" },
  { group: "HĐ ra", code: "INV01", name: "Hóa đơn GTGT", view: "hdra" },
  { group: "HĐ ra", code: "INV02", name: "Có mã cơ quan thuế", view: "hdra" },
  { group: "HĐ ra", code: "INV03", name: "Hóa đơn máy tính tiền", view: "hdra" },
  { group: "HĐ ra", code: "INV04", name: "Hóa đơn từ đơn sàn", view: "omni" },
  { group: "HĐ ra", code: "INV05", name: "Phát hành lẻ và hàng loạt", view: "hdra" },
  { group: "HĐ ra", code: "INV06", name: "Gửi hóa đơn cho người mua", view: "hdra" },
  { group: "HĐ ra", code: "INV07", name: "Điều chỉnh, thay thế, hủy", view: "hdra" },
  { group: "HĐ ra", code: "INV08", name: "Ghi chú ngành đặc thù", view: "hdra" },
  { group: "HĐ ra", code: "INV09", name: "Phiếu chuyển kho nội bộ", view: "kho" },
  { group: "HĐ ra", code: "INV10", name: "Trạng thái truyền CQT", view: "hdra" },
  { group: "HĐ vào", code: "AP01", name: "Hóa đơn đầu vào", view: "hdvao" },
  { group: "HĐ vào", code: "AP02", name: "Gợi ý bóc tách chứng từ", view: "hdvao" },
  { group: "HĐ vào", code: "AP03", name: "Khớp PO – nhập – hóa đơn", view: "hdvao" },
  { group: "HĐ vào", code: "AP04", name: "Cảnh báo MST rủi ro", view: "hdvao" },
  { group: "HĐ vào", code: "AP05", name: "Lưu XML 10 năm", view: "ht" },
  { group: "Sổ", code: "GL01", name: "Chế độ HKD / DN", view: "thue" },
  { group: "Sổ", code: "GL02", name: "Nhật ký chung", view: "so" },
  { group: "Sổ", code: "GL03", name: "Tiền mặt và tiền gửi", view: "nh" },
  { group: "Sổ", code: "GL04", name: "Tuổi nợ phải thu / phải trả", view: "so" },
  { group: "Sổ", code: "GL05", name: "TSCĐ và CCDC", view: "so" },
  { group: "Sổ", code: "GL06", name: "Giá vốn món / lệnh bếp", view: "fnb" },
  { group: "Sổ", code: "GL07", name: "Doanh thu ghi nhận", view: "bc" },
  { group: "Sổ", code: "GL08", name: "Kênh ngoại tệ ghi chú", view: "so" },
  { group: "Sổ", code: "GL09", name: "Chi nhánh", view: "ht" },
  { group: "Sổ", code: "GL10", name: "Khóa sổ kỳ", view: "ht" },
  { group: "Báo cáo", code: "RPT01", name: "KQKD và tiền", view: "bc" },
  { group: "Báo cáo", code: "RPT02", name: "Dashboard chủ hộ", view: "home" },
  { group: "Báo cáo", code: "RPT03", name: "Doanh thu theo kênh", view: "bc" },
  { group: "Thuế", code: "TAX01", name: "Tờ GTGT mô phỏng", view: "thue" },
  { group: "Thuế", code: "TAX02", name: "Tờ 01/CNKD", view: "thue" },
  { group: "Thuế", code: "TAX03", name: "Tạm tính thu nhập", view: "thue" },
  { group: "Thuế", code: "TAX04", name: "Hoa hồng nhân viên", view: "ns" },
  { group: "Thuế", code: "TAX05", name: "Cờ giảm GTGT", view: "thue" },
  { group: "Thuế", code: "TAX06", name: "Xem XML trước khi nộp", view: "thue" },
  { group: "Thuế", code: "TAX07", name: "Bảng kê mua vào bán ra", view: "thue" },
  { group: "Thuế", code: "TAX08", name: "Đơn sàn và COD", view: "omni" },
  { group: "Nhân sự", code: "HR01", name: "Vai trò thu ngân / kho / kế toán", view: "ns" },
  { group: "Nhân sự", code: "HR02", name: "Hoa hồng ca", view: "ns" },
  { group: "Nhân sự", code: "HR03", name: "Ca làm việc", view: "pos" },
  { group: "CRM", code: "CRM01", name: "Điểm và hạng thành viên", view: "crm" },
  { group: "CRM", code: "CRM02", name: "Lịch sử mua", view: "crm" },
  { group: "Hệ thống", code: "SYS01", name: "Chữ ký số HSM", view: "ht" },
  { group: "Hệ thống", code: "SYS02", name: "Nhật ký thao tác", view: "ht" },
  { group: "Hệ thống", code: "SYS03", name: "Hồ sơ MST", view: "ht" },
  { group: "Hệ thống", code: "SYS04", name: "Luồng POS → kho → HĐ → sổ", view: "map" },
  { group: "Hệ thống", code: "SYS05", name: "Gợi ý nghiệp vụ", view: "home" },
];
